config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:edit, :update]

  resources :test_cases do
    get :verify, on: :member
    get :download, on: :member
  end

  root 'home#index'
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Robotic
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to 'Test Case', test_cases_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'Profile', edit_user_path(current_user)
              %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign In', new_user_session_path

app/views/layouts/_notice.html.haml
- if notice
  .alert.alert-warning.alert-dismissible{:role => "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = notice

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RoboticWeb
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    %br
    %br
    %br
    %br
    .container.bottom_margin
      .row
        .col-md-12
          = render 'layouts/notice'
          = yield